on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 146.59.0.136
        port: 21
        username: ${{ secrets.username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /lobby/datapacks/taq_minigames/
